### ISSUE TITLE
"npm test" does not work with react-scripts@2.0 + react-app-rewired

### ISSUE THREAD

**Issue by pablomolnar** [timarney/react-app-rewired#242]
`npm test` throws errors in brand new CRA2.0 app (https://github.com/facebook/create-react-app/issues/3815)

#### 1) Create CRA@2.0 app with react-app-rewired

```bash
cd /tmp
npx create-react-app@next --scripts-version=2.0.0-next.66cc7a90 my-react-app
cd my-react-app
npm install
npm install react-app-rewired --save-dev
```

#### 2) Create a `config-overrides.js` file in the root directory

```javascript
/* config-overrides.js */

module.exports = function override(config, env) {
  //do stuff with the webpack config...
  return config;
}
```

#### 3) 'Flip' the existing calls to `react-scripts` in `npm` scripts
```diff
  /* package.json */

  "scripts": {
-   "start": "react-scripts start",
+   "start": "react-app-rewired start",
-   "build": "react-scripts build",
+   "build": "react-app-rewired build",
-   "test": "react-scripts test --env=jsdom",
+   "test": "react-app-rewired test --env=jsdom"
}
```

### Expected

test ran successfully

### Current behaviour

```bash
> my-react-app@0.1.0 test /private/tmp/my-react-app
> react-app-rewired test --env=jsdom

/private/tmp/my-react-app/node_modules/react-scripts/scripts/utils/createJestConfig.js:35
    roots: srcRoots.map(toRelRootDir),
                    ^

TypeError: srcRoots.map is not a function
    at module.exports (/private/tmp/my-react-app/node_modules/react-scripts/scripts/utils/createJestConfig.js:35:21)
    at Object.<anonymous> (/private/tmp/my-react-app/node_modules/react-app-rewired/scripts/test.js:16:16)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:660:3
npm ERR! Test failed.  See above for more details.
```

**Comment by patroza** [comment]
Same issue here, we also had to remove the `babelTransform` as it refers to babel6, while cra 2.0 is on 7.

**Comment by patroza** [comment]
@Guria so far it seems the only required changes are the paths fix, and upgrading the `babelTransform`/`package.json` to use CRA 2.0 matching babel versions.
webpack4 would be additional work, but getting the above supported would be superb already.

**Comment by leepowell-aviva** [comment]
👍

**Comment by leepowell-aviva** [comment]
The paths issue is fixed in the @next branch, however the error seems to be thrown from using the `babel-preset-react-app` in the `babelTransform.js` file. I'm not fully familiar with the internals of Babel/Webpack, but I have only one version of this package installed in my project and that's the one used by `react-scripts` 2.0.

Changing `rewireJestConfig.js` to point to `react-scripts` 2.0 version of `babelTransform.js` file does not trigger this error, even though both files are almost identical.

I was hoping to be able to provide a fix for this but am a little stumped.

**Comment by timarney** [comment]
@Guria FYI webpack 4

https://github.com/facebook/create-react-app/commit/d1454febd13c8e008e5dec4f13e7d55bf4eb4d18

https://twitter.com/dan_abramov/status/998258353255088128

**Comment by mnemanja** [comment]
I can confirm the behavior.
My react-scripts is on version `2.0.0-next.66cc7a90` and react-app-rewired on `2.0.0`. When running the tests locally everything runs correctly, but when running it on Jenkins I get errors like this:

```
FAIL src/components/containers/units/UnitItem/unitItemActions.test.js
  ● Test suite failed to run

    Cannot find module 'babel-preset-react-app'
      
      at Object.<anonymous> (node_modules/react-app-rewired/scripts/utils/babelTransform.js:14:21)
```

**Comment by timarney** [comment]
Just noting this:
https://github.com/facebook/create-react-app/issues/4511

**Comment by timarney** [comment]
Note: If anyone has interest in leading / maintaining  a 2.0 release @ me .

My time has been and will be limited for this project.  **That is to say considering not doing 2.0 given I can't support it** .  Thanks to all for helping out to date.

**Comment by sowhatdoido** [comment]
I tried installing react-app-rewired `^1.6.2` and react-scripts `2.0.0-next.a671462c`, then manually performing the update found in #243, and everything seems to work fine

**Comment by timarney** [comment]
Moving forward maybe:
https://github.com/arackaf/customize-cra

**Comment by nateshmbhat** [comment]
I found that the error is because of older version of babel which doesn't handle newer versions of react code.

### Here's the fix : 

My problem was of older babel version fixed easily by installing :

    npm i @babel/plugin-proposal-class-properties @babel/preset-react @babel/preset-env @babel/core @babel/plugin-transform-runtime --save-dev

In .babelrc file :

    {
       "presets": [
           "@babel/react" , 
           "@babel/env" , 
       ],
       "plugins": [
           "@babel/plugin-proposal-class-properties"
       ]
    }



Now babel built it successfully after this.
